language: go
dist: xenial
notifications:
  email:
    recipients:
      - middleware@hexonet.net
    on_success: never
    on_failure: always
addons:
  apt:
    update: true
env: GO111MODULE=on GOFLAGS='-mod vendor'
go:
  - "1.12"
  - "1.13"
# Trigger a push build on master and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^dependabot.*$/
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.8
script:
  - ./scripts/validate-go.sh
  - ./scripts/test-go.sh
jobs:
  include:
    - stage: release
      node_js: lts/*
      install:
        - rm -rf ~/.nvm
        - git clone https://github.com/creationix/nvm.git ~/.nvm
        - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
        - source ~/.nvm/nvm.sh
        - nvm install lts/*
      script:
        - npm prune
        - travis_retry npm i
        - npx semantic-release
